name: Deploy Storage Account

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Storage Account with Bicep
      run: |
        az deployment group create \
          --resource-group rg-aueast-ash-01 \
          --template-file 19.05.25_MyAzureSubscription/storage_account.bicep \
          --parameters 19.05.25_MyAzureSubscription/storage_account.bicepparam
