# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_SECRET}}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Deploy Bicep file to Azure
      run: |
        az deployment sub create \
          --location australiaeast \
          --template-file MyDevOpsJourney/19/05/25 - My Azure Subscription Setup/storage_account.bicep
