name: Deploy Virtual Networks

on:
  push:
    branches:
      - main
    paths:
      - infra/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SECRET }}

    - name: Deploy Resource Group
      run: |
        az deployment sub create \
          --location eastus \
          --template-file infra/resourceGroup.bicep


    - name: Deploy VNets to Resource Group
      run: |
        az deployment group create \
          --resource-group ContosoResourceGroup \
          --template-file infra/main.bicep


    - name: Deploy Private DNS Zones
      run: |
        az deployment group create \
          --resource-group ContosoResourceGroup \
          --template-file infra/privateDnsZone.bicep
    
    - name: Deploy Virtual Machines
      run: |
        az deployment group create \
          --resource-group ContosoResourceGroup \
          --template-file infra/vmDeploy.bicep
          --parameters adminUsername='admin' adminPassword='Kom@l123'