name: Deploy Bicep Using .bicepparam

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: Deploy Bicep with Params
        run: |
          az deployment group create \
          --resource-group rg-aueast-ash-01 \
          --template-file 19.05.25_MyAzureSubscription/storage_account.bicep \
          --parameters 19.05.25_MyAzureSubscription/storage_account.bicepparam