name: Deploy Bicep Using .bicepparam

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET }}

      - name: Deploy Bicep with Params
        run: |
          az deployment sub create \
            --location australiaeast \
            --template-file MyDevOpsJourney/19/05/25 - My Azure Subscription Setup/storage_account.bicep \
            --parameters MyDevOpsJourney/19/05/25 - My Azure Subscription Setup/storage_account.bicepparam
